name: DevSecOps - Main - Release on push

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.head_ref || github.ref_name }}]
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Release
        run: npx --yes -p @semantic-release/changelog -p @semantic-release/git semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
